### ISSUE TITLE
华为mate30在集成了该组件的地方用Actions跳转到其他页面就会崩溃

### ISSUE THREAD

**Issue by CalvinAtHome** [supervons/react-native-echarts-pro#1]
华为mate30在集成了该组件的地方用Actions跳转到其他页面就会崩溃
手机： mate 30
版本：Android 10   emui 11

**Comment by supervons** [comment]
hey，man！很高兴你能发现一个bug，能否贴出相关示例代码，以便于我快速复现并修复问题。

**Comment by supervons** [comment]
hey，bro，如果没有回复我就先关掉了，等你贴出来我们再讨论。
