### ISSUE TITLE
使用1.9.0版本加载中国地图会报错

### ISSUE THREAD

**Issue by yuepy** [supervons/react-native-echarts-pro#101]
Cannot read property 'regions' of undefined
查了一下，解决方案有降低Echarts版本，修改echarts依赖文件等等。。。

**Comment by yuepy** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/33448252/233590272-d9fbf2e6-0580-4a6b-a370-89c032834624.png">

**Comment by supervons** [comment]
你好，可以发一下相关 `code`，以便快速排查定位。

**Comment by yuepy** [comment]
已解决，registerMap注册的map名称要跟geo里面的map匹配

**Comment by yuepy** [comment]
<img width="889" alt="image" src="https://user-images.githubusercontent.com/33448252/233816639-7d6e2a86-83e5-4192-9138-19c984926e28.png">
