### ISSUE TITLE
使用中国地图时，多次点击会有几次无法影响click事件

### ISSUE THREAD

**Issue by yuepy** [supervons/react-native-echarts-pro#104]
问题描述：使用中国地图时，有时无法响应onMessage里面的click，断点看只有touchstart，touchend就结束了，而且没有走到on Message方法里面

react-native-charts-pro 【1.9.0】
react-native 【0.71.6】
react-native-swiper 【1.6.0】
Platform 【android】
Demo

const option = {
    tooltip: {
      trigger: 'item'
    },
    geo: [
      {
        map: 'china',
        zoom: 1,
        geoIndex:0,
        layoutCenter: ['50%', '70%'],
        layoutSize: '125%',
        label: {
          show: false,
          color: '#fff',
        },
        itemStyle: {
          borderWidth: 1,
          borderColor: '#1c337f',
          areaColor: '#7AA7FF'
        },
        emphasis: {
          label: {
            show: true,
            color: '#fff'
          },
          itemStyle: {
            borderWidth: 1,
            borderColor: '#fff',
            areaColor: '#53b1f9'
          }
        },
        select: {
          label: {
            show: true,
            color: '#fff'
          },
          itemStyle: {
            borderWidth: 1,
            borderColor: '#fff',
            areaColor: '#53b1f9'
          }
        }
      }
    ],
    visualMap: {
      type: 'piecewise',
      left: 12,
      bottom: 5,
      pieces: [
        { min: 80, max: 100, label: '100+' },
        { min: 60, max: 80, label: ' ' },
        { min: 40, max: 60, label: ' ' },
        { min: 20, max: 40, label: ' ' },
        { min: 0, max: 20, label: '0' }
      ],
      inRange: {
        color: ['#7AA7FF', '#6996FF', '#3E6CFE', '#1256EA', '#003DCC']
      },
      text: ['交易客户数',''],
      textGap: 5,
      textStyle: {
        color: 'rgba(255, 255, 255, .7)',
        fontSize:8,
        lineHeight:16
      },
      itemWidth: 12,
      itemHeight: 6,
      itemGap: 1,
      showLabel: true
    },
    series: [
      {
        name: 'china',
        type: 'map',
        geoIndex: 0,
        data:[{value:100,name:'陕西'}]
      }
    ]
  }

**Comment by yuepy** [comment]
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/33448252/234787793-533975be-5e46-4c90-bbc8-beb5962562ef.png">

**Comment by yuepy** [comment]
<img width="754" alt="image" src="https://user-images.githubusercontent.com/33448252/234788071-f33081fb-8433-40f2-a4bf-267be777799f.png">
网上查解决方案还是更新echarts版本

**Comment by yuepy** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/33448252/234788656-02acbcfc-9c8b-43d1-9c4d-5ad38111bea9.png">
现象是选中西藏省，只触发了高亮没有触发select，select状态还在上一个新疆省，并且没有触发组件的onPress

**Comment by supervons** [comment]
感谢反馈，将会跟进复现并修复该问题，另外，可以提供下`Android`的系统版本吗？

**Comment by yuepy** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/33448252/234802715-52c3d4eb-dc7e-4c41-8daa-b40c3e95b28e.png">
设备信息

**Comment by yuepy** [comment]
估计是echarts本身的问题，查了echarts的issue，里面也出现过移动端click事件没响应的问题，感觉可以从这方面入手查一下

**Comment by supervons** [comment]
的确，`echarts issues` 中有几个和 `click` 相关的，如：

https://github.com/apache/echarts/issues/17046

https://github.com/apache/echarts/issues/16598

但是我在[最小示例](https://supervons.github.io/react-native-echarts-pro-docs/zh-cn/docs/tutorial-map/usage)中却没有复现，能否发下完整`单文件可运行`的代码？

**Comment by yuepy** [comment]
[归档.zip](https://github.com/supervons/react-native-echarts-pro/files/11392416/default.zip)
<img width="607" alt="image" src="https://user-images.githubusercontent.com/33448252/236095735-75bd9672-8b44-4cf8-9a6c-57794be608f6.png">
"react-native": "0.69.3",
"react-native-webview": "^12.0.2",
"react-native-echarts-pro": "1.9.0",
china js路径要改一下，辛苦

**Comment by supervons** [comment]
抱歉，我在相同的版本中没有复现成功；但已经同步到 `ECharts` 最新版 `5.4.2`，后续发布后可以更新试下是否修复该问题。

**Comment by supervons** [comment]
`1.9.1` 版本已发布，`EChats` 版本更新至 `5.2.4`，详见 [Tag-1.9.1](https://github.com/supervons/react-native-echarts-pro/releases/tag/v1.9.1)
