### ISSUE TITLE
5.4.0里 饼图的 label  formatter {d} 值的百分比异常

### ISSUE THREAD

**Issue by Imagine-Tom** [supervons/react-native-echarts-pro#105]
5.4.1里他们修复了这个问题。希望可以集成一下。
谢谢。
label: {
            show: true,
            position: 'inside',
            formatter: '{d}%',
            fontSize: 16,
          },

**Comment by supervons** [comment]
感谢反馈，已有升级至 `5.4.2` 的打算，预计本周内发布，见提交：https://github.com/supervons/react-native-echarts-pro/commit/cb7496b82a46aa0e3e7fcdf1330ec905c5c3b690

**Comment by Imagine-Tom** [comment]
等待。

**Comment by supervons** [comment]
`1.9.1` 版本已发布，`EChats` 版本更新至 `5.2.4`，详见 [Tag-1.9.1](https://github.com/supervons/react-native-echarts-pro/releases/tag/v1.9.1) @Imagine-Tom
