### ISSUE TITLE
关于配置项xAxis > axisLabel > color 无法执行function问题

### ISSUE THREAD

**Issue by Frosv** [supervons/react-native-echarts-pro#108]
版本 1.9.0

``` js
axisLabel: {
          color: function (value, index) {
            console.log(value);
          },
}
```

当前代码在echarts官网是可以运行的，也可以打印出对应参数和做相应处理，但是在react-native-echarts-pro中无法执行打印内容与其他的逻辑判断方法，仓库中的echarts是min版本的不方便找源码是否实现function，希望能看看当前是否是存在问题

**Comment by congshengwu** [comment]
请否是否启用了Hermes?

**Comment by jianxinzhoutiti** [comment]
color: function (value, index) {
            console.log(value);
          },
 function inoperative

**Comment by jianxinzhoutiti** [comment]
打开enableParseStringFunction属性为true，`function (value, index) {
return "#999999"
          },`可以执行
