### ISSUE TITLE
WKWebview注入js脚本（webview 置灰操作），Echarts图标不显示问题

### ISSUE THREAD

**Issue by MMing0310** [supervons/react-native-echarts-pro#109]
iOS端使用WKWebview注入js脚本（webview 置灰操作，实现APP灰白模式）后，Echarts无法正常显示，以下是WKWebview注入js脚本的代码：

#import "WKWebView+blackWhiteModel.h"
#import <objc/runtime.h>

@implementation WKWebView (blackWhiteModel)
+ (void)load {
    Method customMethod = class_getInstanceMethod([self class], @selector(gl_initWithFrame:configuration:));
    Method originMethod = class_getInstanceMethod([self class], @selector(initWithFrame:configuration:));
    method_exchangeImplementations(customMethod, originMethod);//方法交换
}

- (instancetype)gl_initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration *)configuration
{
    BOOL isOpenWhiteBlackModel = [[NSUserDefaults standardUserDefaults] boolForKey:@"kIsShowBlackWhiteModel"];
    if (isOpenWhiteBlackModel) {
        // js脚本
        NSString *jScript = @"var filter = '-webkit-filter:grayscale(100%);-moz-filter:grayscale(100%); -ms-filter:grayscale(100%); -o-filter:grayscale(100%) filter:grayscale(100%);';document.getElementsByTagName('html')[0].style.filter = 'grayscale(100%)';";
        // 注入
        WKUserScript *wkUScript = [[WKUserScript alloc] initWithSource:jScript injectionTime:WKUserScriptInjectionTimeAtDocumentEnd forMainFrameOnly:YES];
                     
        WKUserContentController *wkUController = [[WKUserContentController alloc] init];
           [wkUController addUserScript:wkUScript];
        // 配置对象
        WKWebViewConfiguration *wkWebConfig = [[WKWebViewConfiguration alloc] init];
        wkWebConfig.userContentController = wkUController;
        configuration = wkWebConfig;
        WKWebView *webView = [self gl_initWithFrame:frame configuration:configuration];
        return webView;
    }
    
    return [self gl_initWithFrame:frame configuration:configuration];
}
@end

目前该库是否支持WKWebview注入js脚本，更改Echarts主题样式等问题？

**Comment by supervons** [comment]
1、提供六种基础样式，详见 [themeName](https://supervons.github.io/react-native-echarts-pro-docs/zh-cn/docs/tutorial-basics/props#themename)。

2、思路上建议改变下，因为是基于`react-native-webview`进行注入，为什么在`iOS`端进行修改，应该通过其提供的`API`进行修改，比如通过 [extension](https://supervons.github.io/react-native-echarts-pro-docs/zh-cn/docs/tutorial-basics/props#extension) 进行注入，然后根据业务逻辑进行判断：

<img width="352" alt="image" src="https://github.com/supervons/react-native-echarts-pro/assets/31637849/77fed2c3-8602-4719-8a31-091b8585eb11">

**Comment by MMing0310** [comment]
您好，react-native-webview是基于WKWebview实现的，那我使用原生runtime机制，拦截交换，在WKWebview初始化的时候，直接注入js代码，通过css改变h5的样式，应该是可以的吧？但是注入后，ECharts就失效不显示了，哪怕我什么都不注入，依然无法显示，这是为什么？
(instancetype)gl_initWithFrame:(CGRect)frame configuration:(WKWebViewConfiguration *)configuration
{
BOOL isOpenWhiteBlackModel = [[NSUserDefaults standardUserDefaults] boolForKey:@"kIsShowBlackWhiteModel"];
if (isOpenWhiteBlackModel) {
// js脚本
// NSString *jScript = @"var filter = '-webkit-filter:grayscale(100%);-moz-filter:grayscale(100%); -ms-filter:grayscale(100%); -o-filter:grayscale(100%) filter:grayscale(100%);';document.getElementsByTagName('html')[0].style.filter = 'grayscale(100%)';";
NSString *jScript  = @"";
// 注入
WKUserScript *wkUScript = [[WKUserScript alloc] initWithSource:jScript injectionTime:WKUserScriptInjectionTimeAtDocumentEnd forMainFrameOnly:YES];

  WKUserContentController *wkUController = [[WKUserContentController alloc] init];
     [wkUController addUserScript:wkUScript];
  // 配置对象
  WKWebViewConfiguration *wkWebConfig = [[WKWebViewConfiguration alloc] init];
  wkWebConfig.userContentController = wkUController;
  configuration = wkWebConfig;
  WKWebView *webView = [self gl_initWithFrame:frame configuration:configuration];
  return webView;
}

return [self gl_initWithFrame:frame configuration:configuration];
}

**Comment by supervons** [comment]
方案已提供，可以试一下。

可能是和`react-native-webview`的 `JS` 注入有冲突。
