### ISSUE TITLE
tooltip data use outside chart

### ISSUE THREAD

**Issue by Stackerr** [supervons/react-native-echarts-pro#11]
hello, I'm using your library to adjust project 
but I have question about something.

I checked the module about event. example onPress, onDataZoom 
but I need data about tooltip outside your module 

I try to manipulate your module to listen event about tooltip
but Only receive event are Touch event OnPress or DataZoom.

would you able to get tooltip info if touch event triggered?
that event get outside on your module. that would be great to use my project.

but I really thank you about your sincere feedback on your project
Thank you

**Comment by supervons** [comment]
Can you tell the event's name？

There have a event :

`legendSelectChanged `

**Comment by supervons** [comment]
Too long no reply, wait for new message I will open again.
