### ISSUE TITLE
部分手持pda扫码设备上不显示图表，而我使用react-native-webview组件调用echarts可以显示

### ISSUE THREAD

**Issue by DreamEVA** [supervons/react-native-echarts-pro#118]
系统：android7.1.1
react-native-echarts-pro version: 1.9.1
react-native-webview version:11.26.1

具体的系统信息可以通过邮箱联系我

示例代码
      const option = {
        color:['#1f8afe'],
        xAxis: {
          type: 'value',
          show:false, //不显示坐标轴线、坐标轴刻度线和坐标轴上的文字
          axisTick:{
            show:false//不显示坐标轴刻度线
          },
          axisLine: {
            show: false, //不显示坐标轴线
          },
          axisLabel: {
            show: false, //不显示坐标轴上的文字
          },
        },
        // dataZoom: [
        //   {
        //     type: 'inside',
        //     start: 50,
        //     end: 0,
        //     yAxisIndex: [0],
        //   },
        //   {
        //     start:50,
        //     end:0,
        //     yAxisIndex: [0],
        //   }
        // ],
        yAxis: {
          type: 'category',
          data: ["废渣","医疗废物"],
          axisLabel: {
            interval: 0,
            formatter(value) {
              let ret = '';//拼接加\n返回的类目项
              const maxLength = 5;//每项显示文字个数
              const valLength = value.length;//X轴类目项的文字个数
              const rowN = Math.ceil(valLength / maxLength); //类目项需要换行的行数
              if (rowN > 1) { //如果类目项的文字大于5,
                for (let i = 0; i < rowN; i++) {
                  let temp = '';//每次截取的字符串
                  const start = i * maxLength;//开始截取的位置
                  const end = start + maxLength;//结束截取的位置
                  //这里也可以加一个是否是最后一行的判断，但是不加也没有影响，那就不加吧
                  if(i+1===rowN) {
                    temp = value.substring(start, end-1) + '...';
                  }else{
                    temp = value.substring(start, end) + '\n';
                  }
                  ret += temp; //凭借最终的字符串
                }
                return ret;
              }
              else {
                return value;
              }
            }
          },
          axisTick:{
            show:false//不显示坐标轴刻度线
          },
        },
        grid:{
          left:'21%',
          right:'14%',
          bottom:'10%',
          top:'5%'
        },
        series: [
          {
            data: [200,500],
            type: 'bar',
            barMaxWidth:50,
            label: {
              show: true,
              position: 'right',
              formatter(v) {
                return v.data + 'kg';
              }
            },
          }
        ]
      };
<RNEChartsPro
                ref={ref}
                height={540}
                option={option}
                webViewSettings={{
                  androidLayerType:'hardware' }}/>

**Comment by supervons** [comment]
使用模拟器，同样的版本，依赖包是没问题的，方便提供下具体信息吗？

<img width="185" alt="Snipaste_2023-12-05_11-10-27" src="https://github.com/supervons/react-native-echarts-pro/assets/31637849/1fdcc962-f903-4192-a0e3-f4da138e6f55">

**Comment by DreamEVA** [comment]
我使用react-native-webview调用的echarts是在安卓的主包中放了一个html，路径是通过uri传给webview的
![image](https://github.com/supervons/react-native-echarts-pro/assets/57390572/24cf50ab-a2f3-477a-af82-cfd9ff9a61f4)
![image](https://github.com/supervons/react-native-echarts-pro/assets/57390572/1eae0a69-c6a6-4243-9ca7-c2df36e0bf81)
