### ISSUE TITLE
Does this support third-party extension

### ISSUE THREAD

**Issue by akazwz** [supervons/react-native-echarts-pro#12]
请问这个支持echarts的第三方扩展吗

**Comment by supervons** [comment]
目前暂时不支持三方，如果有需要的话（比如高德地图扩展等），可以提出来。

我会去调研然后在未来版本中更新。

**Comment by supervons** [comment]
Too long no reply, wait for new message I will open again.

**Comment by akazwz** [comment]
> 目前暂时不支持三方扩展，需要什么扩展呢？（比如高德地图扩展等），可以提出来。
> 
> 我会去调研然后在未来版本中更新。

实际上是想要一个 wordcloud 词云的扩展,请问有办法我在本地自己先加上吗

**Comment by akazwz** [comment]
> > 目前暂时不支持三方扩展，需要什么扩展呢？（比如高德地图扩展等），可以提出来。
> > 我会去调研然后在未来版本中更新。
> 
> 实际上是想要一个 wordcloud 词云的扩展,请问有办法我在本地自己先加上吗

找到了,谢谢

**Comment by supervons** [comment]
> > > 目前暂时不支持三方扩展，需要什么扩展呢？（比如高德地图扩展等），可以提出来。
> > > 我会去调研然后在未来版本中更新。
> > 
> > 
> > 实际上是想要一个 wordcloud 词云的扩展,请问有办法我在本地自己先加上吗
> 
> 找到了,谢谢

可以分享一下你的方案，帮助更多有类似需求的人！

**Comment by akazwz** [comment]
@supervons 好的,我说一下我怎么解决的,希望对类似需求的人有帮助.

1. 在 jsdelivr 上找到需要扩展的 min.js包
2. 找到项目的 node_modules/react-native-echarts-pro/src/components/Utils/HtmlWeb.js
3. 有两种方法可以修改,我是直接在HtmlWeb中加入如下:
````html
<script src="https://cdn.jsdelivr.net/npm/echarts@5.2.0/dist/echarts.min.js"></script>
````
这就相当于导入需要的扩展,但是需要联网
第二种就是模仿作者的做法,把js当作字符串输出并引入到HtmlWeb
````html
import * as wordCloud from "../Echarts/echarts-wordcloud"; // wordcloud 引入
...
<script>${wordCloud}</script>
````
这对我来说有用

**Comment by supervons** [comment]
OK，后续我会增加一个属性来动态传入拓展，可以是cdn地址，也可以是文件字符串；
感谢你的分享Thanks♪！

**Comment by akazwz** [comment]
> OK，后续我会增加一个属性来动态传入拓展，可以是cdn地址，也可以是文件字符串；
> 
> 感谢你的分享Thanks♪！

好的，期待👏

**Comment by supervons** [comment]
1.7.3已发布

支持动态传参扩展，使用说明：[README](https://github.com/supervons/react-native-echarts-pro/blob/master/README_CN.md#extension)

示例：[DEMO](https://github.com/supervons/ExploreRN/blob/master/src/components/charts/chartsExtension.js)

**Comment by akazwz** [comment]
> 1.7.3已发布
> 
> 支持动态传参扩展，使用说明：[README](https://github.com/supervons/react-native-echarts-pro/blob/master/README_CN.md#extension)
> 
> 示例：[DEMO](https://github.com/supervons/ExploreRN/blob/master/src/components/charts/chartsExtension.js)

🎉🎉🎉
