### ISSUE TITLE
formatter导致图表白屏不显示

### ISSUE THREAD

**Issue by lxverycool** [supervons/react-native-echarts-pro#122]
问题：图表首次渲染时，yAxis的axisLabel如果formatter传入函数，会导致图表不显示，但是第二次手动调用setNewOption方法传入相同的配置，就显示正常。（使用文档中的enableParseStringFunction也无效）
版本：react native版本0.62.2，react-native-echarts-pro版本1.9.1
目前解决办法：传入一个没有formatter的初始配置，finished方法中监听首次渲染完成了再手动将正确配置写进去

**Comment by supervons** [comment]
你好，请按照[issues规范](https://github.com/supervons/react-native-echarts-pro/issues/6)提供下详细信息，方便排查。

**Comment by kingka** [comment]
+1 , RN升级到0.72.2 后，同样的代码在iOS这段，只要写了formatter 就是显示不出来...把formatter里面的内容删了就行，但是需要linechart显示tooltip自定义样式和点击事件。。。。难搞

**Comment by supervons** [comment]
请更新至1.9.2再尝试。 @lxverycool @kingka
