### ISSUE TITLE
如何按需引入所需要的图表？

### ISSUE THREAD

**Issue by we6288815** [supervons/react-native-echarts-pro#127]
大家好，使用库的时候该如何按需引入所需要的库？
我当前只需要柱状图，但是打包出来的内容里面包含了地图等不需要的数据，导致包体积占用较大;

react-native-echarts-pro【1.9.2】
react-native version【0.59.10】

**Comment by supervons** [comment]
前往 [ECharts在线定制](https://echarts.apache.org/zh/builder.html) 选择需要的模块并下载。
将生成的产物按 #2 中所述进行处理。

**Comment by we6288815** [comment]
@supervons 这是否意味着我需要fork当前仓库，然后做出相应修改后自行发布？

**Comment by supervons** [comment]
是的，相对定制化的需求，可以自行更改。
