### ISSUE TITLE
如何获取图例高度？

### ISSUE THREAD

**Issue by Molly29** [supervons/react-native-echarts-pro#129]
### 因为需求关系，这块不能使用scroll类型图例，并且由于图例数量不确定，图例过多会和下面图形重叠；

react-native-echarts-pro【1.9.1】
Platform【android】
Demo：

![示例图片](https://github.com/user-attachments/assets/2a8d40d9-9599-440d-b615-9426a60c1218)

### Current Behavior
目前echarts官方提供了一个可以获取动态图例高度的方法，得到的这个高度的值可以设置给grid.top。
![解决方法](https://github.com/user-attachments/assets/16a4a89e-b6b5-4787-ae6a-bef2713a0948)[https://github.com/apache/echarts/issues/19755](url)
但是使用react-native-echarts-pro无法调用官方示例的方法。

### Expected Behavior
希望能支持调用官方的方法，或者给出获取图例的API

**Comment by supervons** [comment]
暂不支持，后续可以考虑加进去。

可先配置图例翻页：
```js
legend: {
      type: "scroll", // 设置图例翻页
}
```

DEMO：[ExploreRN](https://github.com/supervons/ExploreRN/blob/master/src/components/charts/charts.tsx)
