### ISSUE TITLE
RNEChartsPro doesn't work when the type is radar

### ISSUE THREAD

**Issue by linhaimin** [supervons/react-native-echarts-pro#14]
when the type is radar, RNEChartsPro displays blank

dependent version: 
"react-native": "0.64.2",
"react-native-echarts-pro": "^1.7.1",
"react-native-webview": "^11.13.1"

**Comment by supervons** [comment]
```
npm install react-native-echarts-pro@1.7.3
```

Demo：

```javascript
import React from "react";
import { View } from "react-native";
import RNEChartsPro from "react-native-echarts-pro";
export default function ChartsComponent() {
  const pieOption = {
    legend: {
      data: ["Allocated Budget", "Actual Spending"],
    },
    radar: {
      // shape: 'circle',
      indicator: [
        { name: "Sales", max: 6500 },
        { name: "Administration", max: 16000 },
        { name: "Information Technology", max: 30000 },
        { name: "Customer Support", max: 38000 },
        { name: "Development", max: 52000 },
        { name: "Marketing", max: 25000 },
      ],
    },
    series: [
      {
        name: "Budget vs spending",
        type: "radar",
        data: [
          {
            value: [4200, 3000, 20000, 35000, 50000, 18000],
            name: "Allocated Budget",
          },
          {
            value: [5000, 14000, 28000, 26000, 42000, 21000],
            name: "Actual Spending",
          },
        ],
      },
    ],
  };

  return (
    <View style={{ backgroundColor: "#fff", height: 300, paddingTop: 25 }}>
      <RNEChartsPro
        onPress={res => alert(JSON.stringify(res))}
        legendSelectChanged={res => alert(res)}
        height={250}
        option={pieOption}
      />
    </View>
  );
}


```

**Comment by linhaimin** [comment]
@supervons Hi, this is my simulator info.
`

Name: Pixel_XL_API_30

CPU/ABI: Google APIs Intel Atom (x86)

Path: D:\Android\Avd\.android\avd\Pixel_XL_API_30.avd

Target: google_apis [Google APIs] (API level 30)

Skin: pixel_xl_silver

SD Card: 512 MB

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: pixel_xl

hw.lcd.width: 1440

hw.initialOrientation: Portrait

image.androidVersion.api: 30

tag.id: google_apis

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Pixel XL API 30

hw.gpu.mode: auto

hw.ramSize: 4096

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 2560

vm.heapSize: 384

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images\android-30\google_apis\x86\

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Pixel_XL_API_30

hw.lcd.density: 560

hw.arc: false

hw.device.hash2: MD5:f78477654d5471c3d7f705251d14e72f

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

disk.dataPartition.size: 6G

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes`

**Comment by supervons** [comment]
Do you still have the problem? 

I use AS emulator, but  it work's.

I don't know how to review it. But i will open this bug until review and fix it.

API：30
version：android 11


![image](https://user-images.githubusercontent.com/31637849/138199163-67536ed5-4a3c-4623-b84f-7a0b944311ad.png)

**Comment by supervons** [comment]
Open it again when there is new information.
