### ISSUE TITLE
想知道你们对 echarts.min.js 做了什么处理？

### ISSUE THREAD

**Issue by GreatAuk** [supervons/react-native-echarts-pro#2]
因为有定制的需求（https://echarts.apache.org/zh/builder.html）, 大多数图表还是用不上的。
我直接把定制后下载的代码或者直接使用[完整的代码](https://cdn.bootcdn.net/ajax/libs/echarts/5.1.2/echarts.min.js)替换项目中的 echarts.min.js 是没有用的，会报错。

**Comment by supervons** [comment]
Hello，对echarts.min.js没有做任何处理的，但是要切记，替换的时候，把它当成一个模板字符串导出即可！
如下图所示（替换后可能点击事件和部分监听需要按最新版本修改，在项目的src/components/Echarts/renderChart.js中）：
![image](https://user-images.githubusercontent.com/31637849/124406011-b6558400-dd72-11eb-8b9a-511424982f27.png)

**Comment by ks4na** [comment]
@supervons 

你好，我想问一下，当前版本（ `v1.7.7`, `echarts 版本 5.2.1`）的源码中 `echarts.min.js` 中使用 `export default` 导出时是如何对源码进行处理的，上面的回复中说直接`export default` , 现在好像已经不是这么处理的了。

我找了一份 5.2.1 源码，全局替换了如下几个地方：

```
\ 替换成 \\
` 替换成 \`
```

但是与源码中 `echarts.min.js` 的全部字符个数对比了一下，有出入：

源码中 `echarts.min.js` 的总字符数是 1011504 个：

<img width="461" alt="截屏2022-02-07 下午8 40 01" src="https://user-images.githubusercontent.com/28475898/152790226-fb436970-6f14-4afd-8dab-77fd930ea03d.png">

我基于 5.2.1 版本 echarts 作了上面的替换操作后的总字符数是 1011509 个：

<img width="449" alt="截屏2022-02-07 下午8 45 24" src="https://user-images.githubusercontent.com/28475898/152790646-1baf5722-7bcf-496a-8b9f-6e3e41c9ebad.png">


想请教一下你是如何处理的。

**Comment by supervons** [comment]
只是做了这个处理，把下图里面的产物中的 `echarts.min.js` 拿过来，封装导出使用。

产物地址：https://raw.githubusercontent.com/apache/echarts/5.2.1/dist/echarts.min.js

通过`git` 工具比较后，并没有发现文本的差异。

字数不一样可能有格式化工具对于空格进行了处理。


<img width="856" alt="image" src="https://user-images.githubusercontent.com/31637849/152911470-06085c7c-21c5-4415-bdd4-6c86689fba58.png">

准备在下一个版本同步升级到最新 `echarts` 版本。
