### ISSUE TITLE
包无法更新1.7.4版本

### ISSUE THREAD

**Issue by winterping** [supervons/react-native-echarts-pro#23]
您好，我想使用1.7.4新添加的功能，但是yarn更新的时候显示包的版本只有到1.7.3，npm 查看包所有版本也只到1.7.3，请问这个该如何处理？

**Comment by supervons** [comment]
你好，目前最新版本已经发布，我怀疑可能是`lock`文件造成的。

尝试使用`yarn add react-native-echarts-pro@1.7.4` 或者`npm install react-native-echarts-pro@1.7.4` 更新。

**Comment by winterping** [comment]
不行呢，两种方式都没办法下载下来。都会提示没有这个版本

**Comment by supervons** [comment]
看一看镜像源地址呢？

**Comment by winterping** [comment]
是源不对的问题，切换成这个源可以下下来了！十分感谢！！！
