### ISSUE TITLE
安卓真机5.1不显示图表

### ISSUE THREAD

**Issue by xilanzouwei** [supervons/react-native-echarts-pro#25]
react-native-echarts-pro【1.7.4】
react-native version【0.63.4】
react-native-webview 【11.0.2】
Platform【android】
模拟器上可以正常显示，高版本的真机也可以显示

**Comment by supervons** [comment]
我这里没有5.1的设备。

有可能 `webview` 版本太高了，看看 `webview` 运行普通网页能不能显示。

或者降低 `webview` 看看图表能不能显示。

**Comment by xilanzouwei** [comment]
试了下，普通网页也不能显示，￣へ￣
