### ISSUE TITLE
安卓模拟器上图表可以显示，真机上不显示

### ISSUE THREAD

**Issue by ListenLY** [supervons/react-native-echarts-pro#28]
react-native-echarts-pro【1.7.3】
react-native version【0.59.5】
react-native-webview 【6.11.1】
Platform【android】
System【10，11】
Demo：
/**
 * 柱状
 */
export const pieOptionColumn = (xData, yData, max) => {
    return {
        color: [theme.orangeColor],
        tooltip: {
            trigger: 'axis',
            axisPointer: {            // 坐标轴指示器，坐标轴触发有效
                type: 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
            }
        },
        grid: {
            left: '1%',
            right: '1%',
            bottom: '3%',
            top: '8%',
            containLabel: true
        },
        xAxis: [
            {
                type: 'category',
                data: xData,
                axisTick: {
                    alignWithLabel: true
                }
            }
        ],
        yAxis: [
            {
                type: 'value',
                max: max,
            }
        ],
        series: [
            {
                name: '金额',
                type: 'bar',
                barWidth: '30%',
                data: yData,
            }
        ]
    }
};

import React from "react";
import { View } from "react-native";
import RNEChartsPro from "react-native-echarts-pro";

  return (
    <View style={{ height: 300, paddingTop: 25 }}>
       <RNEChartsPro
                                onPress={res => {
                                    console.log(res)
                                }}
                                legendSelectChanged={res => console.log(res)}
                                width={this.state.chartsWidth}
                                height={this.state.chartsHeight}
                                option={pieOptionColumn(xData, yData, this.state.moneyMax)}
                            />
    </View>
  );
}

**Comment by supervons** [comment]
- 试一下看看普通网易是否能显示；
- 尝试更新下 `react-native-webview` 至最新版本；

**Comment by supervons** [comment]
太久没有回复，等有回复或者类似情况再打开。
