### ISSUE TITLE
formatter 在 JSON.stringify 后竟然消失了

### ISSUE THREAD

**Issue by sej1228** [supervons/react-native-echarts-pro#30]

**Comment by supervons** [comment]
有例子吗？

用法是安装这个走的吗？

https://github.com/supervons/react-native-echarts-pro/blob/master/README_CN.md#formattervariable

![image](https://user-images.githubusercontent.com/31637849/149687479-d1cbe8b8-85ee-4907-9401-a4f4dadca991.png)

**Comment by supervons** [comment]
太久没有回复，有新回复时，我们再继续讨论！
