### ISSUE TITLE
一个界面加载多个图表，超级慢，甚至渲染不出来

### ISSUE THREAD

**Issue by jackchen0120** [supervons/react-native-echarts-pro#32]
多图表渲染延迟，加载很慢，图表切换有时加载不出来，请问是什么原因，有什么可以优化的地方

**Comment by supervons** [comment]
大概是多少个呢？之前有遇到某些机型有这个问题。

本组件基于 `echarts` + `webview` 实现，性能瓶颈在于 `webview`。

**Comment by supervons** [comment]
太久没回复，有新动向再讨论。
