### ISSUE TITLE
formatter's in tooltip, axisLabel are being reset.

### ISSUE THREAD

**Issue by hyunahOh** [supervons/react-native-echarts-pro#36]
```
  const testOption = {
    tooltip: {
      backgroundColor: 'rgba(255,255,255,0.8)',
      borderColor: '#668BEE',
      borderWidth: 1,
      padding: [5, 10],
      textStyle: {
        color: '#24283C',
        fontSize: 12,
      },
      trigger: 'item',
      formatter: function (a) { // Changed here!!!
        return 'hihi';
      },
    },
    series: [
      {
        name: 'Source',
        type: 'pie',
        legendHoverLink: true,
        hoverAnimation: true,
        avoidLabelOverlap: true,
        startAngle: 180,
        radius: '55%',
        center: ['50%', '35%'],
        data: [
          {value: 105.2, name: 'android'},
          {value: 310, name: 'iOS'},
          {value: 234, name: 'web'},
        ],
        label: {
          normal: {
            show: true,
            textStyle: {
              fontSize: 12,
              color: '#23273C',
            },
          },
        },
        emphasis: {
          lable: {
            show: true,
            fontSize: 12,
            color: '#668BEE',
          },
          itemStyle: {
            show: true,
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowColor: 'rgba(0, 0, 0, 0.5)',
          },
        },
      },
    ],
  };
```

[First]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/40825346/159417284-6ec52706-9af9-4a22-b94a-7c5e8a27e721.png">

[Second]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/40825346/159417323-b812d6fe-31cb-463e-95a3-481f5216735b.png">

I set custom formatter like code, and this works for a while and a few seconds later, it shows default tooltip formatter. I tried `setNewOption`, and same result.

**Comment by supervons** [comment]
Could you tell me `setNewOption` params?

@hyunahOh

**Comment by hyunahOh** [comment]
@supervons 

I didn't call `setNewOption`.

actually I changed second parameter of setOption. and it works. Can you guess why?

```
// node_modules/react-native-echarts-pro/src/components/Echarts/renderChart.js line:81
// myChart.setOption(option, true, true);
 myChart.setOption(option, false, true);
```

**Comment by supervons** [comment]
I knew, i will fix it this week. 

you can see more: [Apeach Echarts](https://echarts.apache.org/en/api.html#echartsInstance.setOption)

You can use `react-native-echarts-pro@1.8.0` first.

**Comment by hyunahOh** [comment]
@supervons 

oh I see. It was because of `notMerge` param.

Thanks for quick and detail reply! your package is awesome.

**Comment by supervons** [comment]
Thanks，Have a good trip!
