### ISSUE TITLE
ios上渲染不出来报错：Webview Process Terminated

### ISSUE THREAD

**Issue by fairySusan** [supervons/react-native-echarts-pro#38]
ios上渲染不出来报错：Webview Process Terminated

**Comment by fairySusan** [comment]
1.ios上渲染不出来报错：Webview Process Terminated
2.ios上setNewOption不起作用

**Comment by supervons** [comment]
请提供一下必要的环境信息：

可以参考： https://github.com/supervons/react-native-echarts-pro/issues/6

**Comment by fairySusan** [comment]
我调了一下，在ipad上这行代码的结果是false
在renderChart.js文件里 `let isiOS = !!u.match(/\\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端` 
所以在ipad上setNewOption()不起作用

react-native-echarts-pro 版本是1.8.2

机子：ipad（第五代）ios 15.0

**Comment by fairySusan** [comment]
> 我调了一下，在ipad上这行代码的结果是false 在renderChart.js文件里 `let isiOS = !!u.match(/\\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端` 所以在ipad上setNewOption()不起作用
> 
> react-native-echarts-pro 版本是1.8.2
> 
> 机子：ipad（第五代）ios 15.0

**Comment by fairySusan** [comment]
1.ios上渲染不出来报错：Webview Process Terminated， 这个的解决办法是：
[https://stackoverflow.com/questions/61723317/react-native-webview-process-terminated](https://stackoverflow.com/questions/61723317/react-native-webview-process-terminated)

**Comment by fairySusan** [comment]
> 请提供一下必要的环境信息：
> 
> 可以参考： #6
我调了一下，在ipad上这行代码的结果是false
在renderChart.js文件里 let isiOS = !!u.match(/\\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
所以在ipad上setNewOption()不起作用

react-native-echarts-pro 版本是1.8.2

机子：ipad（第五代）ios 15.0

**Comment by fairySusan** [comment]
我调了一下，在ipad上这行代码的结果是false
在renderChart.js文件里 let isiOS = !!u.match(/\\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
所以在ipad上setNewOption()不起作用

react-native-echarts-pro 版本是1.8.2

机子：ipad（第五代）ios 15.0

**Comment by fairySusan** [comment]
> 请提供一下必要的环境信息：
> 
> 可以参考： #6

我调了一下，在ipad上这行代码的结果是false
在renderChart.js文件里 let isiOS = !!u.match(/\\(i[^;]+;( U;)? CPU.+Mac OS X/); //ios终端
所以在ipad上setNewOption()不起作用

react-native-echarts-pro 版本是1.8.2

机子：ipad（第五代）ios 15.0

**Comment by supervons** [comment]
1. 使用模拟器，`isiOS` 是 `true`，下面是 `navigator.userAgent` 信息：
<img width="187" alt="image" src="https://user-images.githubusercontent.com/31637849/160552351-14415380-3147-4ea1-99b2-888ce20b1530.png">
模拟器信息：
<img width="159" alt="image" src="https://user-images.githubusercontent.com/31637849/160552571-2de51cf9-0ac9-4826-9fac-b52ad56132f7.png">

能否使用 `iPAD（第五代）`截取一下 `navigator.userAgent` 中的信息，以便兼容 `setNewOption `。

2. `Webview Process Terminated` 针对这个问题，能否看下该设备上，使用 `WebView` 能否正常加载网页呢？

**Comment by fairySusan** [comment]
@supervons 
Mozilla/5.0 (Macintosh; Intel Mac OS X
10_15_6) AppleWebKit/605.1.15
(KHTML, like Gecko)


2. 解决了第一个问题后，第二个问题也没有了

**Comment by supervons** [comment]
试一下我这次提交，用 `native` 的方式判断系统：https://github.com/supervons/react-native-echarts-pro/commit/a045cf08b4cf91cf22aabb7ef62a9cde27d36c2e

本周内将会发布新版本。

**Comment by supervons** [comment]
@fairySusan 

1.8.3 已发布：
```javascript
 npm install react-native-echarts-pro@1.8.3
```
