### ISSUE TITLE
axisLabel不支持formatter属性

### ISSUE THREAD

**Issue by zengyuehao** [supervons/react-native-echarts-pro#44]

**Comment by zengyuehao** [comment]
react-native-echarts-pro 【1.8.1】;
react-native 【0.67.1】;
react-native-webview 【11.17.2】;
平台 【安卓】;

**Comment by zengyuehao** [comment]
`defaultOption = {
            title: [], //
            legend: {
                data: ['发电功率'],
                show: true,
                z: 3,
                icon: "circle",
            },

            color: [
                "#0ac860",
                "#ed3333",
                "#2fa4ed",
                "#9e5ed9",
                "#00b0a7",
                "#ed3472",
                "#4878f9",
            ],
            tooltip: {
                trigger: "axis",

                axisPointer: {
                    animation: false,
                },
            },
            xAxis: [
               {
                type: "time",
                splitLine: {
                    show: true,
                },
                axisLine: {
                    show: false,
                },
                axisTick: {
                    show: false,
                    interval: 3,
                },
                // maxInterval: 3 * 60 * 60 * 1000,
                axisLabel: {
                    // 将拿到的时间戳转换成时间
                     formatter: function (value, index) {
                         let date = new Date(value);
                         let hour = date.getHours();
                         let minutes = date.getMinutes();
                         if (hour < 10) {
                             hour = "0" + hour;
                         }
                         if (minutes < 10) {
                             minutes = "0" + minutes;
                         }
                         return hour + ":" + minutes + "{img|}";
                     },
                    // 显示最大值和最小值
                    showMinLabel: true,
                    showMaxLabel: true,
                    fontSize: 10
                },
            }
            ],
            yAxis: [
                name: item.unit,
                nameTextStyle: {
                    color: "#1B2232",
                    fontSize: 12,
                },
                max: 200,
                interval: 100,
                min: 0,
                axisLine: {
                    show: false
                },
                axisTick: {
                    show: false
                },
                type: "value",
                boundaryGap: [0, "100%"],
                splitLine: {
                    show: true,
                },
            ],
            series: [
               type: "line",
                unit: item.unit,
                hoverAnimation: false,
                showSymbol: false,
                smooth: true,
                symbolSize: 4,
                data: item.data,
                areaStyle: {
                    color: 'red',
                    opacity: 0.5,
                },
                itemStyle: {
                    color: 'red',
                },
            ],
        }`

**Comment by zengyuehao** [comment]
使用axislabel中的formatter属性后数据消失了

**Comment by zengyuehao** [comment]
`{
                type: "time",
                splitLine: {
                    show: true,
                },
                axisLine: {
                    show: false,
                },
                axisTick: {
                    show: false,
                    interval: 3,
                },
                // maxInterval: 3 * 60 * 60 * 1000,
                axisLabel: {
                    // 将拿到的时间戳转换成时间
                    formatter: function (value, index) {
                        let date = new Date(value);
                        let hour = date.getHours();
                        let minutes = date.getMinutes();
                        if (hour < 10) {
                            hour = "0" + hour;
                        }
                        if (minutes < 10) {
                            minutes = "0" + minutes;
                        }
                        return hour + ":" + minutes + "{img|}";
                    },
                    // 显示最大值和最小值
                    showMinLabel: true,
                    showMaxLabel: true,
                    fontSize: 10
                },
            }`

**Comment by zengyuehao** [comment]
`

  {
                type: "time",
                splitLine: {
                    show: true,
                },
                axisLine: {
                    show: false,
                },
                axisTick: {
                    show: false,
                    interval: 3,
                },
                // maxInterval: 3 * 60 * 60 * 1000,
                axisLabel: {
                    // 将拿到的时间戳转换成时间
                    formatter: function (value, index) {
                        let date = new Date(value);
                        let hour = date.getHours();
                        let minutes = date.getMinutes();
                        if (hour < 10) {
                            hour = "0" + hour;
                        }
                        if (minutes < 10) {
                            minutes = "0" + minutes;
                        }
                        return hour + ":" + minutes + "{img|}";
                    },
                    // 显示最大值和最小值
                    showMinLabel: true,
                    showMaxLabel: true,
                    fontSize: 10
                },
            }




`

**Comment by zengyuehao** [comment]
react-native-echarts-pro 【1.8.2】;
react-native 【0.67.1】;
react-native-webview 【11.15.0】;
平台 【安卓】;

**Comment by supervons** [comment]
是否启用了 `Hermes` 引擎，可以查看：https://github.com/supervons/react-native-echarts-pro/issues/35
