### ISSUE TITLE
有什么方法可以获取到 echartsInstance吗

### ISSUE THREAD

**Issue by zengyuehao** [supervons/react-native-echarts-pro#46]

**Comment by supervons** [comment]
目前暂时无法暴露 `echartsInstance`，可以说一说需求一起讨论实现。

**Comment by zengyuehao** [comment]
目前遇到的问题是切换数据时上一次的数据残留在了图上，无法使用echartsInstance.clear()

**Comment by supervons** [comment]
试试更新的时候，加上参数：
```jsx
this.echarts.setNewOption(options, { notMerge: true });
```

另外有个好消息，目前已经找到获取 `echartsInstance` 的方法，将在下个版本发布！

**Comment by zengyuehao** [comment]
> 试试更新的时候，加上参数：
> 
> ```js
> this.echarts.setNewOption(options, { notMerge: true });
> ```
> 
> 另外有个好消息，目前已经找到获取 `echartsInstance` 的方法，将在下个版本发布！

我想问一下数据获取保存在redux中，使用useEffect监听保存在redux的数据并进行数据处理后，我这边更新了多次option导致图像显示和最后一次获取到的数据不一致

**Comment by supervons** [comment]
- 数据获取指的是从接口获取吗？如果是的话可以排查下接口返回的顺序。

- 更新是使用 `setNewOption` 进行更新的吗？


可以提供一个简单示例，以方便我进行复现并修改。

**Comment by zengyuehao** [comment]
> - 数据获取指的是从接口获取吗？如果是的话可以排查下接口返回的顺序。
> 
> - 更新是使用 `setNewOption` 进行更新的吗？
> 
> 
> 可以提供一个简单示例，以方便我进行复现并修改。

setNewOption配置了没有作用，我是使用useState去配置option的

**Comment by zengyuehao** [comment]
> * 数据获取指的是从接口获取吗？如果是的话可以排查下接口返回的顺序。
> * 更新是使用 `setNewOption` 进行更新的吗？
> 
> 可以提供一个简单示例，以方便我进行复现并修改。

暂时没有办法提供示例，业务场景比较复杂。目前我的解决方法是拿到数据后再渲染<ECharts>

**Comment by supervons** [comment]
`1.8.4` 已发布，支持获取 `echartsinstance`！

更多请查看全新上线的文档库：[react-native-echarts-pro-docs](https://supervons.github.io/react-native-echarts-pro-docs/zh-cn/docs/tutorial-basics/method/#getinstance)
