### ISSUE TITLE
长时间在后台再打开webview白屏

### ISSUE THREAD

**Issue by VictorYuan666** [supervons/react-native-echarts-pro#54]
iOS 偶现这个问题 搜了下应该是下面这个issue
https://github.com/react-native-webview/react-native-webview/issues/2298

能否加下这个代码
`<WebView
  source={{ uri: 'https://reactnative.dev' }}
  onContentProcessDidTerminate={(syntheticEvent) => {
    const { nativeEvent } = syntheticEvent;
    console.warn('Content process terminated, reloading', nativeEvent);
    this.refs.webview.reload();
  }}
/>
 `

**Comment by supervons** [comment]
```javascript
      <WebView
        source={{ uri: "https://reactnative.dev" }}
        onContentProcessDidTerminate={syntheticEvent => {
          const { nativeEvent } = syntheticEvent;
          console.warn("Content process terminated, reloading", nativeEvent);
          this.refs.webview.reload();
        }}
      />
```
这里的 `refs` 引用对象并没有定义，这样会报错的吧。

**Comment by supervons** [comment]
长时间没回复，有最新消息前先关闭。
