### ISSUE TITLE
怎么动态设置柱形图的颜色和 折线图的区域颜色渐变

### ISSUE THREAD

**Issue by fefuming** [supervons/react-native-echarts-pro#60]
itemStyle: {
    color: function(params){
        if(params.value>12){
            return '#c20919'
        }else{
            return '#0CF49B'
        }
    }
},
这种方式设置不生效

**Comment by supervons** [comment]
可以使用如下属性试试：
```javascript

  lineStyle: {
    color: {
      type: "linear",
          x: 0,
          y: 0,
          x2: 0,
          y2: 1,
          colorStops: [
        {
          offset: 0,
          color: "red", // 0% 处的颜色
        },
        {
          offset: 0.5,
          color: "blue", // 100% 处的颜色
        },
      ],
    },
  }
```

可以参考：[series-line.lineStyle](https://echarts.apache.org/zh/option.html#series-line.lineStyle)

**Comment by supervons** [comment]
太久没回复，有新进展再沟通。
