### ISSUE TITLE
怎样添加各种on事件啊

### ISSUE THREAD

**Issue by ng520tx** [supervons/react-native-echarts-pro#62]
图例交互事件：

1） legendselectchanged : 切换图例选中状态后的事件 (注：图例组件用户切换图例开关会触发该事件,不管你有没有选择，点击了就触发)

2）legendselected：例组件用legendSelect 图例选中后的事件，即点击显示该图例时，触发就生效。

3）legendunselected： legendUnSelect 图例取消选中后的事件。

4）datazoom：数据区域缩放后的事件。缩放视觉映射组件。

5）datarangeselected：selectDataRange 视觉映射组件中，range 值改变后触发的事件。

6）timelinechanged：timelineChange 时间轴中的时间点改变后的事件。

7）timelineplaychanged：timelinePlayChange 时间轴中播放状态的切换事件。

8）restore： restore 重置 option 事件。

9）dataviewchanged：工具栏中数据视图的修改事件。

10）magictypechanged：工具栏中动态类型切换的切换事件。

**11）geoselectchanged：geo 中地图区域切换选中状态的事件（用户点击选中会触发该事件。）。

12）geoselected：geo 中地图区域选中后的事件（使用dispatchAction可触发此事件，用户点击不会触发此事件（用户点击事件请使用 geoselectchanged））。

13）geounselected：geo 中地图区域取消选中后的事件，使用dispatchAction可触发此事件，用户点击不会触发此事件（用户点击事件请使用 geoselectchanged）。**

14）pieselectchanged：series-pie 中饼图扇形切换选中状态的事件，用户点击选中会触发该事件。

15）pieselected：series-pie 中饼图扇形选中后的事件，使用dispatchAction可触发此事件，用户点击不会触发此事件（用户点击事件请使用 pieselectchanged）。

16）pieunselected：series-pie 中饼图扇形取消选中后的事件，使用dispatchAction可触发此事件，用户点击不会触发此事件（用户点击事件请使用 pieselectchanged）。

17）mapselectchanged： series-map 中地图区域切换选中状态的事件，用户点击选中会触发该事件。

18）mapselected：series-map 中地图区域选中后的事件，使用dispatchAction可触发此事件，用户点击不会触发此事件（用户点击事件请使用 mapselectchanged）。

19）mapunselected：series-map 中地图区域取消选中后的事件，使用dispatchAction可触发此事件，用户点击不会触发此事件（用户点击事件请使用 mapselectchanged）。

20）axisareaselected：平行坐标轴 (Parallel) 范围选取事件，

当进行坐标轴范围选取时，可以用如下方式获取当前高亮的线所对应的 data indices （即 series 的 data 中的序号列表）。

**Comment by supervons** [comment]
很不错的建议，正在开发自定义Event，预计下个版本发布。（两周内，9月10日前）

**Comment by supervons** [comment]
`1.8.6` 版本已支持自定义 `Event`，使用 `eventActions` 属性，如 `finished` 事件：
```javascript
  eventActions={{
    finished:()=>{
      alert(1)
    }
  }}
```
`Demo` 可参考：
[eventActions-Demo](https://github.com/supervons/ExploreRN/blob/master/src/components/charts/charts.js)

后续会详细在文档里介绍。
