### ISSUE TITLE
希望能加上

### ISSUE THREAD

**Issue by ng520tx** [supervons/react-native-echarts-pro#63]
geoselectchanged：geo 中地图区域切换选中状态的事件（用户点击选中会触发该事件。）。

geoselected：geo 中地图区域选中后的事件（使用dispatchAction可触发此事件，用户点击不会触发此事件（用户点击事件请使用 geoselectchanged））。

geounselected：geo 中地图区域取消选中后的事件，使用dispatchAction可触发此事件，用户点击不会触发此事件（用户点击事件请使用 geoselectchanged）。

**Comment by supervons** [comment]
很不错的建议，正在开发自定义`Event`，预计下个版本发布。（两周内，9月10日前）

**Comment by supervons** [comment]
`1.8.6` 版本已支持自定义 `Event`，使用 `eventActions` 属性，如 `finished` 事件：
```javascript
  eventActions={{
    finished:()=>{
      alert(1)
    }
  }}
```
`Demo` 可参考：
[eventActions-Demo](https://github.com/supervons/ExploreRN/blob/master/src/components/charts/charts.js)

后续会详细在文档里介绍。
