### ISSUE TITLE
添加更多的操作可能

### ISSUE THREAD

**Issue by ng520tx** [supervons/react-native-echarts-pro#64]
renderChart.js  中加入:
更改click事件 加入更多参数 有助于提高图形的操作度，希望作者采纳
    myChart.on('click', (params)=>{
      const clickParams = {
        // 数据名，类目名
        name: params.name || "",
        // 传入的数据值
        value: params.value || 0,
        componentType: params.componentType||"",
        // 系列类型。值可能为：'line'、'bar'、'pie' 等。当 componentType 为 'series' 时有意义。
        seriesType: params.seriesType||"",
        // 系列在传入的 option.series 中的 index。当 componentType 为 'series' 时有意义。
        seriesIndex: params.seriesIndex|| 0,
        // 系列名称。当 componentType 为 'series' 时有意义。
        seriesName: params.seriesName||"",
        // 数据在传入的 data 数组中的 index
        dataIndex: params.dataIndex||0,
        // 传入的原始数据项
        data: params.data||{},
        // sankey、graph 等图表同时含有 nodeData 和 edgeData 两种 data，
        // dataType 的值会是 'node' 或者 'edge'，表示当前点击在 node 还是 edge 上。
        // 其他大部分图表中只有一种 data，dataType 无意义。
        dataType: params.dataType||"",
        // 数据图形的颜色。当 componentType 为 'series' 时有意义。
        color: params.color||"",
      };
      window.ReactNativeWebView.postMessage(JSON.stringify(clickParams));
    });

**Comment by supervons** [comment]
收到反馈，计划于下一版本（`1.8.7，9月28日前`）发布！
