### ISSUE TITLE
请问一下，作者是否对 echarts.min.js 做了特殊处理

### ISSUE THREAD

**Issue by ruofee** [supervons/react-native-echarts-pro#65]
请教一下，作者对 echart.min.js 除了给 ` 加上转义之外，还有做一些其他的处理吗?

**Comment by supervons** [comment]
可以查看 https://github.com/supervons/react-native-echarts-pro/issues/2。

主要是：

1. 使用`export default`导出模板字符串；

2. 
```
\ 替换成 \\
` 替换成 \`
```

**Comment by ruofee** [comment]
> 可以查看 #2
> 
> 主要是：
> 
> 1. 使用`export default`导出模板字符串；
> 
> ```
> \ 替换成 \\
> ` 替换成 \`
> ```

感谢解答！
