### ISSUE TITLE
热词云展示不稳定

### ISSUE THREAD

**Issue by lanjinglingxx** [supervons/react-native-echarts-pro#67]
问题：
热词云展示不稳定，开发环境下小几率展示
react-native：0.66.0
react-native-echarts-pro:1.8.5
react-native-webview:11.22.7
热词拓展文件（无法上传）
echarts-wordcloud.min

**Comment by supervons** [comment]
热词拓展文件能共享一份吗？

还有代码也可以提供下，方便快速复现，感谢。

更多信息可以按照规范提供下https://github.com/supervons/react-native-echarts-pro/issues/6

**Comment by lanjinglingxx** [comment]
https://github.com/ecomfe/echarts-wordcloud

**Comment by supervons** [comment]
使用我的词云文件测试下：

[ExploreRN-WordCloud](https://github.com/supervons/ExploreRN/blob/master/src/components/charts/echarts-wordcloud.min.js)

**Comment by lanjinglingxx** [comment]
不行，白屏

**Comment by lanjinglingxx** [comment]
文件能本地拓展吗，之前试过一直报错

**Comment by lanjinglingxx** [comment]
cant found echarts from node_models

**Comment by lanjinglingxx** [comment]
问题解决了 谢谢

**Comment by supervons** [comment]
@lanjinglingxx 方案方便分享一下吗？以便后续遇到这个问题的人参考。

**Comment by lanjinglingxx** [comment]
直接下载的https://github.com/ecomfe/echarts-wordcloud文件放入本地会报错cant found echarts from node_models，所以我就让人把文件放在服务器上，但是这样在网络状态不好或者请求数据过多的情况下，会导致echarts有可能不显示。但是你给的文件可以放在本地（我看了一下，发现你处理过了），所以问题一下子解决了

**Comment by supervons** [comment]
OK。感谢反馈，后续我文档补充一下两种使用方式。
