### ISSUE TITLE
ios 渲染失败

### ISSUE THREAD

**Issue by David881903** [supervons/react-native-echarts-pro#68]
react-native-echarts-pro【1.8.5】
react-native version【0.59.10】
react-native-webview 【10.10.2】
Platform【ios】

ios 数据量超过12万 折线图渲染失败
xAxis: {
		type: 'value',
		minInterval: 1,
		axisLabel: {
			hideOverlap: true,
		},
},
使用type: 'category',是可以渲染，但是使用type: 'value' 就渲染失败

**Comment by supervons** [comment]
数据`Demo`能提供下吗？

方便定位。
