### ISSUE TITLE
ref 属性不存在

### ISSUE THREAD

**Issue by sunny-token** [supervons/react-native-echarts-pro#69]
react-native-echarts-pro【1.8.6】
react-native version【0.69.4】
react-native-webview 【11.23.0】
Platform【ios】
<img width="787" alt="image" src="https://user-images.githubusercontent.com/19677491/191636452-9fe62c65-4447-4784-8866-48824ce990a0.png">
代码：
`<RNEChartsPro
        ref={chartRef}
        option={numOption}
      />`

**Comment by supervons** [comment]
`Typescript`的吗？

**Comment by sunny-token** [comment]
@supervons 是的

**Comment by supervons** [comment]
找到`node_modules`中的该组件目录下的`index.d.ts`，增加下面红框的试试：

<img width="394" alt="image" src="https://user-images.githubusercontent.com/31637849/191637829-0ceb2721-1210-49b8-a8e2-92f38cba44af.png">

**Comment by sunny-token** [comment]
谢谢，这样加了是不报错了，但是这样的话，新项目都需要改下，能在node_modules中新增下吗？

**Comment by supervons** [comment]
计划于下一版本（1.8.7，9月28日前）默认增加并发布！

**Comment by sunny-token** [comment]
好的，谢谢，非常给力！
