### ISSUE TITLE
在FlatList中，数据分页加载，每当加载新数据时，新数据的第一个图表总是空白

### ISSUE THREAD

**Issue by gufengpiaoyi** [supervons/react-native-echarts-pro#73]
react-native-echarts-pro【1.8.4】
react-native version【0.61.0】
react-native-webview 【7.4.3】
Platform【Android】
System【11】

**Comment by supervons** [comment]
可能和代码写的渲染时机有关，如果能提供最小的可运行的单`JS`示例代码，我可以更快定位是组件问题还是写法问题。

**Comment by gufengpiaoyi** [comment]
> 可能和代码写的渲染时机有关，如果能提供最小的可运行的单`JS`示例代码，我可以更快定位是组件问题还是写法问题。

找到问题了，图表width设置的100%，改成屏幕宽度就好了，issue我关了
