### ISSUE TITLE
Typescript定义问题

### ISSUE THREAD

**Issue by jypleo** [supervons/react-native-echarts-pro#74]
为啥props没有定义width属性，
<Container width={props.width}>
里面的width分明是通过props传进来的啊

**Comment by supervons** [comment]
感谢反馈，下一个版本（1.8.8,预计2022年10月20日前发布）将会增加上。

**Comment by supervons** [comment]
1.8.8 版本已发布！
```
npm install react-native-echarts-pro@1.8.8
```
