### ISSUE TITLE
安卓兼容问题

### ISSUE THREAD

**Issue by jypleo** [supervons/react-native-echarts-pro#78]
设备: vivo x9i
安卓版本: 24(7.1.2)
设备webview版本: 55

现象就是直接不显示，跟踪到问题发现是
  for(let temp in ${JSON.stringify(props.eventArrays || "")}){
      myChart.on(temp, (params)=>{
        const clickParams = {
          ...params,
          type: temp
        };
        window.ReactNativeWebView.postMessage(JSON.stringify(clickParams));
      });
    }
这串代码引起的
继续深入发现是  ...params导致的
猜测是低版本webview不支持 ... 语法

**Comment by jypleo** [comment]
再提一个问题，麻烦能不能支持设置字体 我利用extension本来也实现了
 var styles = document.createElement('style');
    styles.innerHTML = '@font-face{font-family:"DINCondensed-Bold";src:url("file:///android_asset/fonts/DINCondensed-Bold.otf");}';
    document.getElementsByTagName('head')[0].appendChild(styles);
但 安卓手机有时候会莫名奇妙偶现不显示 因为extension代码是插入在html标签外的

**Comment by supervons** [comment]
感谢反馈。

针对第一个问题，确实有可能是低版本浏览器不支持`ES6`的新语法，后续会考虑兼容一下低版本。

第二个问题字体的也在计划中，将会在后续版本发布，敬请关注更新通知。
