### ISSUE TITLE
期望扩展字体样式

### ISSUE THREAD

**Issue by NemoZhong** [supervons/react-native-echarts-pro#79]
通过extension方式插入script在html外部，会较频繁地偶现图表渲染不出来的情况，猜测是script在html外部执行顺序，或者HtmlWeb和extensionScript不是同一时间生成的导致图表绘制还没绘制完再次绘制出现的问题。

期望在htmlWeb开个口子配置script  或者  font-face自定义

定位问题图片:
![image](https://user-images.githubusercontent.com/44050946/198226604-7ff73853-391a-4732-87c4-84673177a7dd.png)

解决问题图片:
![image](https://user-images.githubusercontent.com/44050946/198226753-d4180773-66bd-493a-9bce-dc005375240d.png)

code: 
```
const fileName = Platform.select({
  ios: `DINCondensed-Bold.otf`,
  android: `file:///android_asset/fonts/DINCondensed-Bold.otf`,
});

// echart字体设置
const extension = [
  `
    var styles = document.createElement('style');
    styles.innerHTML = '@font-face{font-family:"DINCondensed-Bold";src:url("${fileName}");}';
    document.getElementsByTagName('head')[0].appendChild(styles);
  `,
];

<RNEChartsPro
      extension={extension}
      option={config}
      height={arcHeight}
      webViewSettings={{
        scrollEnabled: false,
      }}
  />

```

**Comment by NemoZhong** [comment]
![image](https://user-images.githubusercontent.com/44050946/198230740-db73c149-2298-45b4-ad55-8c80c7b76460.png)
通过频繁改变source可以复现图表经常不渲染的问题

**Comment by NemoZhong** [comment]
react-native-echarts-pro【1.8.8】
react-native version【0.66.21】
react-native-webview 【11.23.0】
Platform【android】
System【11】

**Comment by supervons** [comment]
感谢反馈，字体问题目前已接到反馈，#78。

目前在计划中，将会在后续版本发布，敬请关注更新通知。

**Comment by supervons** [comment]
`1.8.9` 之后的版本已支持动态字体！
