### ISSUE TITLE
事件不能触发

### ISSUE THREAD

**Issue by J3020605821** [supervons/react-native-echarts-pro#83]
问题：点击事件不能触发
"react-native-echarts-pro": "^1.8.7",
"react-native": "0.69.6",
 "react-native-webview": "11.23.0",
平台;linux
系统版本;Ubuntu 20.04.4 LTS

**Comment by J3020605821** [comment]
![图片](https://user-images.githubusercontent.com/104178424/201462580-c64b6c4a-88df-4b72-bc57-3c0cbf8f42f9.png)

**Comment by J3020605821** [comment]
望回复

**Comment by J3020605821** [comment]
还有一个组件的点击事件不触发：
![图片](https://user-images.githubusercontent.com/104178424/201462890-679ce0cc-bb77-4aa2-9dd3-aaa1b0dd6b84.png)

**Comment by youngerbyte** [comment]
1.eventActions中不要拿click和onclick去接收，接收后点击时里面就报错，此sdk文档说明不详细造成使用错误后web报错但为抛出，所以开发者感知不到
2.click需要拿onPress接收，例如：
<RNEChartsPro 
            ref={chartRef} 
            height={props.height} 
            option={props.option} 
            onPress={(params) => {
              console.warn('✅click:'+JSON.stringify(params));
            }}
            eventActions={{
               finished:()=>{
                 console.warn('✅finished');
              },
            }}/>;

**Comment by supervons** [comment]
如楼上所说，`legendSelectChanged`，`onDataZoom`, `onPress` 其实都无需用 `eventActions`，直接使用即可，后续会在文档中详细说明。

另外，对于文档有任何改进可以关注 https://github.com/supervons/react-native-echarts-pro-website。
