### ISSUE TITLE
【setOption 可能存在问题 仍然存在】是否考虑修复一下

### ISSUE THREAD

**Issue by youngerbyte** [supervons/react-native-echarts-pro#88]
问题见：https://github.com/supervons/react-native-echarts-pro/issues/82
修复见：https://github.com/supervons/react-native-echarts-pro/commit/c396eac7fcb0d622d788bd7cfb201a7976b8f79a

**Comment by supervons** [comment]
OK，可以提一个`PR`到主分支，我后续测试验证没问题后会合并。

**Comment by supervons** [comment]
感谢提供方案，已合并并初步验证通过，完整测试后会在后续版本发布。

详细见： 99ae9ccb79f9eed794f14fa1a1d68acc94282f31
