### ISSUE TITLE
图表无法正常展示 

### ISSUE THREAD

**Issue by 1974892005** [supervons/react-native-echarts-pro#89]
图表无法正常展示 刚开始以为是webwiew没加载 改了一下是echart 没有生成；

react-native-echarts-pro【1.8.9】
react-native version【0.70.5】
react-native-webview 【11.23.1】
Platform【android | Ios】
System【12 | 16】
Demo：
import React from "react";
import { View } from "react-native";
import RNEChartsPro from "react-native-echarts-pro";
export default function ChartsComponent() {
  const [Caiwu, setCaiwu] = useState([111, 222, 333, 444])
    const Caiwu_e = {
        height: 150,
        title: {
            show: false
        },
        textStyle: echartInit.textStyle,
        color: echartInit.color,
        legend: echartInit.legend,
        toolbox: echartInit.toolbox,
        tooltip: {
            ...echartInit.tooltip,
            // trigger: 'item',
        },
        xAxis: {
            type: 'category',
            data: ['Mon', 'Tue', 'Wed', 'Thu']
            , ...echartInit.xAxis
        },
        yAxis: {
            type: 'value', ...echartInit.yAxis
        },
        // grid: echartInit.grid,
        series: [
            {
                ...echartInit.series,
                data: Caiwu,
                name: '测试2',
                type: 'bar',
                itemStyle: {
                    color: AppColor.echarts.blue
                }
            }
        ],
    };

  };

  return (
    <View style={{ height: 300, paddingTop: 25 }}>
     <RNEChartsPro height={240} option={Caiwu_e}
                    webViewSettings={{
                        style: {
                            backgroundColor: AppColor.TP,
                        }
                    }}
                />
    </View>
  );
}

![image](https://user-images.githubusercontent.com/25133430/208243355-b664e52d-09f7-48d0-84ac-a56684e055e4.png)
![image](https://user-images.githubusercontent.com/25133430/208243354-4868bcf6-14ed-4401-a3e8-2a5790caa399.png)

**Comment by supervons** [comment]
代码里的 `echartInit` 和 `AppColor.echarts` 对象从哪里引用的呢？

可以先看下[教程](https://supervons.github.io/react-native-echarts-pro-docs/zh-cn/docs/intro/)，运行下示例`demo`，和 `PC` 版本的示例可能有些许出入。
