### ISSUE TITLE
实例未提供resize方法，无法动态改变图表高度

### ISSUE THREAD

**Issue by Dream-nb** [supervons/react-native-echarts-pro#97]
current: dispatchAction: ƒ dispatchAction(action)
getInstance: ƒ getInstance(functionName, params)
setNewOption: ƒ setNewOption(option, optionSetting)
[[Prototype]]: Object[[Prototype]]: Object

**Comment by supervons** [comment]
图表的实例已经通过 `getInstance` 暴露出来，所以可以改变图表高度，但是需要注意，图表高度和外层容器高度应该同时改变。

参考文档=》[resize](https://supervons.github.io/react-native-echarts-pro-docs/zh-cn/docs/tutorial-basics/method#resize)
